### PR TITLE
setup sentry for JS

### PR DESCRIPTION
**Pull request by samandmoore**
okay! this sets up sentry in our JS code too!

based on this https://github.com/rails/webpacker/blob/master/docs/env.md it looks like we can use `process.env.BLAH` and it will read the values from our compilation process's env. this works for me locally, so i'm hoping it will be good during a deploy.

there's more stuff we can look into to add data about the user or context when there's an error https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/identify-user/

and lastly, i set up a plugin to upload sourcemaps to sentry https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/ -- i think i did it correctly 🤞🏻

### CODE REVIEW

**Comment by samandmoore** [comment]
some examples

https://sentry.io/organizations/stoop-video/issues/2046705901/?project=5526105&query=is%3Aunresolved
https://sentry.io/organizations/stoop-video/issues/2046703806/?project=5526105&query=is%3Aunresolved

**Comment by kfinn** [comment]
happy to see this merged already! but do you have a sense of how this would do handling things that happen outside of a react render?

like, if some twilio room event triggers an error or an incoming actioncable message?

**Comment by kfinn** [comment]
(I have read no documentation, just the code you wrote, and I don't have it in me to find the answer for myself right this second, so I thought I'd be lazy and ask)

**Comment by samandmoore** [comment]
Yup. The docs say that it will hook into the standard browser unhandled exception extension points too.

**Pull request merged**
